name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
      - name: Install dependencies
        run: npm ci
      - name: run and record tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: false

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}